<?php
echo '<div class="indexbar"></div>';
echo '<div class="navback-1"></div>';
echo '<div class="navback-2"></div>';
echo '';
echo '<button class="hamburger" id="hamburger"></button>';
echo '<div class="barnav" style="height: 30px"></div>';
echo '';
echo '<div class="modal" id ="modal-content" style="display:none;">';
echo '<div class="titlerow">';
echo '<div class="flex-container">';
echo '<div class="spacer"></div>';
echo '<div class="spacer"></div>';
echo '<div style="font-size:3.5em; line-height:150%; padding-top:4px"><a href="/" class="nav">RYAN PENG</a></div>';
echo '<div class="spacer"></div>';
echo '<div class="spacer"></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:2.875em; line-height:220%;"><a href="/about" class="nav">ABOUT</a></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:2.875em; line-height:220%"><a id="hamwork" href="/#work" class="hamburger nav">WORK</a></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:2.875em; line-height:220%"><a href="/archive" class="nav">ARCHIVE</a></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:2.875em; line-height:220%"><a href="/misc" class="nav">MISC</a></div>';
echo '<div class="flex-child"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="titlerow barnav fixed-top">';
echo '<div class="flex-container">';
echo '<div class="spacer"></div>';
echo '<div class="spacer"></div>';
echo '<div style="font-size:2.5em; line-height:150%; padding-top:4px"><a href="/" class="nav">RYAN PENG</a></div>';
echo '<div class="spacer"></div>';
echo '<div class="spacer"></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:1.875em; line-height:220%;"><a href="/about" class="nav">ABOUT</a></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:1.875em; line-height:220%"><a href="/#work" class="nav">WORK</a></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:1.875em; line-height:220%"><a href="/archive" class="nav">ARCHIVE</a></div>';
echo '<div class="flex-child"></div>';
echo '<div style="font-size:1.875em; line-height:220%"><a href="/misc" class="nav">MISC</a></div>';
echo '<div class="flex-child"></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<script>';
echo '//hamburger';
echo 'var hcoll = document.getElementsByClassName("hamburger");';
echo 'var ii;';
echo '';
echo 'for (ii = 0; ii < hcoll.length; ii++) {';
echo 'hcoll[ii].addEventListener("click", function() {';
echo 'this.classList.toggle("hamactive");';
echo '})};';
echo '';
echo 'var hmodal = document.getElementById("modal-content");';
echo 'var hbtn = document.getElementById("hamburger");';
echo '';
echo 'hbtn.onclick = function() {';
echo 'if (hmodal.style.display === "flex") {';
echo 'hmodal.style.display = "none";';
echo '} else {';
echo 'hmodal.style.display = "flex";';
echo '}';
echo '}';
echo '';
echo 'var hworkbtn = document.getElementById("hamwork");';
echo 'hworkbtn.onclick = function() {';
echo 'if (hmodal.style.display === "flex") {';
echo 'hmodal.style.display = "none";';
echo 'hbtn.classList.toggle("hamactive");';
echo '} else {';
echo 'hmodal.style.display = "flex";';
echo '}';
echo '}';
echo '';
echo '//imagefade';
echo 'function isInViewport(element) {';
echo 'const rect = element.getBoundingClientRect();';
echo 'return (';
echo 'rect.top >= 0 &&';
echo 'rect.left >= 0 &&';
echo 'rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&';
echo 'rect.right <= (window.innerWidth || document.documentElement.clientWidth)';
echo ');';
echo '}';
echo '';
echo 'const fadebox = document.getElementsByClassName("scrollfade");';
echo 'const fadeanchors = document.getElementsByClassName("fadeanchor");';
echo '';
echo 'document.addEventListener("scroll", function() {';
echo 'for (i = 0; i < fadeanchors.length; i++) {';
echo 'if (isInViewport(fadeanchors[i])) {';
echo 'fadebox[i].classList.add("loadfade2")';
echo '}';
echo '}});';
echo '';
echo '//fadecookie';
echo 'function getCookie(cname) {';
echo 'let name = cname + "=";';
echo 'let decodedCookie = decodeURIComponent(document.cookie);';
echo 'let ca = decodedCookie.split(';');';
echo 'for(let jj = 0; jj <ca.length; jj++) {';
echo 'let c = ca[jj];';
echo 'while (c.charAt(0) == ' ') {';
echo 'c = c.substring(1);';
echo '}';
echo 'if (c.indexOf(name) == 0) {';
echo 'return c.substring(name.length, c.length);';
echo '}';
echo '}';
echo 'return "";';
echo '}';
echo '';
echo 'let indexvisit = document.cookie;';
echo 'var loadfades = document.getElementsByClassName("loadfade");';
echo 'var lfdelays = document.getElementsByClassName("lfdelay");';
echo 'var j;';
echo 'var ij;';
echo 'if (getCookie("indexvisit") === "true") {';
echo 'for (j = loadfades.length-1; j < loadfades.length && j >= 0; j--) {';
echo 'loadfades[j].classList.remove("loadfade")';
echo '};';
echo 'for (ij = lfdelays.length-1; ij < lfdelays.length && ij >= 0; ij--) {';
echo 'lfdelays[ij].classList.remove("lfdelay")';
echo '}};';
echo 'document.cookie = "indexvisit=true; SameSite=Lax; Secure";';
echo '';
echo '//scrollcolor';
echo 'const debounce = (fn) => {';
echo 'let frame;';
echo 'return (...params) => {';
echo 'if (frame) {';
echo 'cancelAnimationFrame(frame);';
echo '}';
echo 'frame = requestAnimationFrame(() => {';
echo 'fn(...params);';
echo '});';
echo '}';
echo '};';
echo '';
echo 'const storeScroll = () => {';
echo 'let perc = window.scrollY / (document.body.clientHeight - window.innerHeight) * 100;';
echo 'document.documentElement.setAttribute('style', `--scrollpos: ${perc}`);';
echo '}';
echo '';
echo 'document.addEventListener('scroll', debounce(storeScroll), { passive: true });';
echo '';
echo 'storeScroll();';
echo '';
echo 'var jsscrollpos = getComputedStyle(document.documentElement).getPropertyValue('--scrollpos');';
echo '</script>';
?>